CatalaLang/catala-language-server

- package.json
- server/src/dune
- server/src/state.ml
This PR adds default indentation strategy and adds support for clerk.toml files in order to properly handle file includes.
> Miscellaneous fixes and add support to clerk.toml 

- server/src/server.ml
This PR fixes two bugs:
- a data-race issue that occurs when a document is changed and the document in saved just after;
- an issue with UTF16 encoded string which would be interpreted as UTF8 by breaking the consistency of internal buffers maintained by linol.
> Miscellaneous fixes

- server/src/jump.ml
- server/src/server.ml
- server/src/state.ml
This PR follows the introduction of modules definition in toml files (c.f. https://github.com/CatalaLang/catala/pull/663) and add support so that the LSP server is able to untangle included intermediate catala files and correctly display errors in such files.
> Add toml module support

- server/src/server.ml
- server/src/utils.ml
This PR fixes an issue where the external call to `catala-format` would fail on large files.
This is due to a concurrency issue that only occurs when pipe communication with an external process gets clogged.
> Rework code formatting glue to fix issue on large files

- package.json
- server/src/jump.ml
- server/src/server.ml
- server/src/state.ml
- syntaxes/en.xml
- syntaxes/fr.xml
This PR adds several AST traversals that were missing and, hence, didn't provide jump-to locations for some expressions.
In particular, structures and enums, as well as their inner fields, are now fully handled. It is now also well referenced and hover pop-ups are less confusing.
> Improve jump-to references 

- package-lock.json
- package.json
- src/extension.ts
This PR adds a check that tests if the catala-lsp is found either in path or locally and display an error message if neither are available.
This will be useful towards the packaging of the extension.
> Display an error message when catala-lsp is not found

- src/extension.ts
I apparently forgot to call `client.start()`.
> Fix issue in entrypoint script

- server/src/main.ml
With https://github.com/CatalaLang/catala/pull/725 merged, we can switch to more idiomatic vscode error messages.
> Switch to LSP error reporting format

- server/src/jump.ml
- server/src/position_map.ml
- server/src/server.ml
- server/src/state.ml
- server/src/utils.ml
This PR removes the naive map of position that was used to lookup types/declarations and replaces it with a better data-structure similar to patricia tries that uses ranges as prefixes.
~WIP: the new structure uncovered strange inconsistencies that we silently ignored and needs to be addressed before merging this work.~
Edit: The PR is now in a good shape and imo ready to be merged. In particular, looking up declarations/references/hovering now works much better.
> Replace naive position map with better data structure

- .github/workflows/ci.yml
- catala-lsp.opam
- package-lock.json
- package.json
The current `vscode-test` stub was broken by the use of `p-queue` (promise queue, a dependency when implementing the "run test" feature).
The current p-queue is not compatible with commonjs2 builds, which we use.
This PR pins p-queue to 6.6.2, which is the last version that supports a commonjs build, and adds a CI job that runs `vscode-test` 
Ultimately we should use ESM for packaging our plugin but the support for this in vscode is still not yet completely mature (?) -- see for instance https://github.com/microsoft/vscode/issues/130367 and https://code.visualstudio.com/updates/v1_94#_esm-is-shipping-for-vs-code
> Fix `vscode-test` setup and add CI job

- server/src/jump.ml
- server/src/position_map.ml
This PR is  a follow up of https://github.com/CatalaLang/catala/pull/734 that needs to be merged beforehand.
It adds the support for lambda binders that weren't considered before which would leave holes in the "jump-to" and hovering over expressions.
> Correctly handle lambda binders

- server/src/server.ml
- server/src/state.ml
This PR maintains the latest valid context of a program. 
This fixes the situation where you are not able to query anything while you're trying to develop and your current buffer is in an invalid state (syntactically or semantically). With this patch you are still able to hover & lookup definitions/declarations.
However, some positions may become inconsistent but (I believe that) the benefits outweigh this issue. This will be tackled later on when the document processing gets refactored.
> Keep around the latest valid program and jump table

- server/src/main.ml
- server/src/state.ml
This PR was a low hanging fruit that allows LSP to notify catala's warnings, e.g.,
Make sure to update catala to the latest master's branch
> Add LSP notifications for warnings

- package.json
- server/src/utils.ml
- src/extension.ts
This PR adds two vscode configuration entries:
- catala.catalaFormatPath
- catala.lspServerPath
which allows the user to harcode path to the respective executables in order to bypass OS-related "limitations".
> Add path configuration

- .github/workflows/ci.yml
- catala-lsp.opam
- package-lock.json
- server/src/dune
- server/src/jump.ml
- server/src/position_map.ml
- server/src/state.ml
- server/test/dune
- server/test/test.ml
This PR adds support for scope definitions jumping.
It also fixes some miscellaneous bugs and removes linol's dev opam pinning. 
In particular, two bugs were found in the position map data structure. A test was added for it.
> Add support for scope definition jumping

- src/defaults.ts
- test-case-parser/examples/francais.catala_fr
- test-case-parser/examples/test_case_french.catala_fr
- test-case-parser/test_case_parser_lib_atd.ml
This will parametrize the test generator (that emits catala code from the ATD representation of the test structure) to emit either french or english sources, according to the original source language.
> Multi language test generation

- src/TestFileEditor.tsx
- src/generated/test_case.ts
- src/style.css
- src/testCaseCompilerInterop.ts
- test-case-parser/test_case.atd
This PR proposes a few usability improvements
- prevents opening the "welcome" dialog when a file is nonempty, and parsing is not in error (i.e. the catala file is valid) but no tests are returned by the parser (because the contents of the file does not conform to our expectation for test cases).
Instead it will show a warning
- improves styling for the 'new test' wizard
> Input and UI improvements

- Makefile
- server/src/jump.ml
- server/src/position_map.ml
- server/src/server.ml
- server/src/state.ml
- server/src/type_printing.ml
- server/test/test.ml
This PR adds pretty markdown on scope hovering instead of displaying a weird <struct> message.
Before:
After:
And, as per usual, a bunch of misc. refactoring and fixes comes along.
> Prettify scope hovering

- src/testCaseCompilerInterop.ts
- test-case-parser/test_case_parser_lib_atd.ml
Fixes the remaining paths that were hard-coded for the initial CNAF demo.
> Remove clerk run hack

- src/TestEditor.tsx
- src/TestFileEditor.tsx
- src/generated/test_case.ts
- src/style.css
- test-case-parser/test_case.atd
- test-case-parser/test_case_parser_lib.ml
- test-case-parser/testcase.ml
This PR adds a description to the test objects (as an attribute).
Descriptions are updated on blur to keep a responsive UI (add a quiescence period or something...?)
Test description is escaped through ocaml's `String.quote` -- it might be worth adapting attribute strings to dovetail with that.
> Add test description 

- src/TestEditor.tsx
- src/TestFileEditor.tsx
- src/TestOutputsEditor.tsx
- src/generated/test_case.ts
- src/i18n/messages.ts
- src/testCaseCompilerInterop.ts
- src/testCaseEditor.ts
- test-case-parser/test_case.atd
This prompts the user to save the current buffer before running a test as the 'run test' commands operates on files and not the buffer's text, so transparently running the file's contents was confusing for the user.
This PR also handles the enhances the cancellation handling
> Check clean buffer before test run

- catala-lsp.opam
- server/src/debug_evaluation.ml
- server/src/debug_interpret.ml
- server/src/main_dap.ml
- server/src/state.ml
- server/src/type_printing.ml
- syntaxes/code_en.xml
- syntaxes/code_fr.xml
- syntaxes/en.xml
- syntaxes/fr.xml
- syntaxes/types_en.xml
- syntaxes/types_fr.xml
- test-case-parser/test_case_parser_lib.ml
This PR fixes the compilation and adapt the LSP and debugger to the stdlib feature merged in Catala.
It also add a hard dependency to `clerk` which must be accessible through the environment by the extension.
> Adapt to Catala stdlib addition

- .github/workflows/ci.yml
- dune
as for Catala: CI must fail on warnings, dev shouldn't, release shouldn't but shouldn't silence them either.
the lack of this setup made unhandled operator additions in Catala get unnoticed here.
I really can't understand how these defaults were chosen in dune 🤷🏿
> Fix ocaml warn/error options
